// js/drugs.js
// 약물 검색기에서 사용할 데이터베이스입니다. 언제든 추가/수정 가능합니다.

const DRUG_DB = [
    { name: "AMC", potency: 375 }, { name: "AMC", potency: 625 },
    { name: "acetazolamide", potency: 250 }, { name: "acetylcysteine", potency: 200 },
    { name: "allopurinol", potency: 100 }, { name: "aluminum hydroxide", potency: 200 },
    { name: "aminophylline", potency: 100 }, { name: "amitriptyline", potency: 10 },
    { name: "amlodipine", potency: 5 }, { name: "atenolol", potency: 50 },
    { name: "azathioprine", potency: 50 }, { name: "benazepril", potency: 10 },
    { name: "bezafibrate", potency: 200 }, { name: "biphenyl-dimethyl-dicarboxylate(레포틸)", potency: 25 },
    { name: "bromhexin", potency: 8 }, { name: "C.pheniramine", potency: 2 },
    { name: "calcitriol(본키) (ug)", potency: 0.25 }, { name: "calcium carbonate", potency: 500 },
    { name: "camostat", potency: 100 }, { name: "carprofen", potency: 25 }, { name: "carprofen", potency: 75 },
    { name: "cefixime", potency: 100 }, { name: "cephalexin", potency: 500 },
    { name: "cephradine", potency: 500 }, { name: "cerenia(maropitant)", potency: 16 }, { name: "cerenia(maropitant)", potency: 24 },
    { name: "cetirizine", potency: 10 }, { name: "ciprofloxacin", potency: 250 },
    { name: "clindamycin", potency: 150 }, { name: "clopidogrel", potency: 75 },
    { name: "codeine", potency: 5 }, { name: "colchicine", potency: 0.6 },
    { name: "cyclosporin(사이폴엔)", potency: 25 }, { name: "cyclosporin(아토피카)", potency: 10 },
    { name: "cyproheptadine orotate", potency: 1.5 }, { name: "danazol", potency: 200 },
    { name: "digoxin", potency: 0.25 }, { name: "diltiazem hydrochloride", potency: 30 },
    { name: "doxycline", potency: 100 }, { name: "enalapril", potency: 10 },
    { name: "enrofloxacin", potency: 50 }, { name: "entresto", potency: 200 },
    { name: "famciclovir", potency: 250 }, { name: "famotidine", potency: 20 },
    { name: "firocoxib", potency: 57 }, { name: "fluoxetine", potency: 20 },
    { name: "furosemide", potency: 40 }, { name: "marbofloxacin", potency: 20 }, { name: "marbofloxacin", potency: 10 },
    { name: "tamsulosin", potency: 0.2 }, { name: "telmisartan", potency: 40 },
    { name: "theophylline", potency: 200 }, { name: "thiamine HCl", potency: 10 },
    { name: "TMS", potency: 10 }, { name: "tolvaptan", potency: 30 },
    { name: "topiramate", potency: 100 }, { name: "torsemide", potency: 5 },
    { name: "tramadol", potency: 50 }, { name: "tranexamic acid", potency: 250 },
    { name: "trazodone", potency: 25 }, { name: "trazodone", potency: 50 },
    { name: "trilostane(정품/가품)", potency: 10 }, { name: "trilostane(정품/가품)", potency: 60 },
    { name: "tylosin tartrate", potency: 60 }, { name: "UDCA", potency: 200 },
    { name: "zonisamide", potency: 100 },
    { name: "gabapentin", potency: 100 }, { name: "gabapentin", potency: 300 },
    { name: "hydralazine", potency: 50 }, { name: "hydrochlorothiazide", potency: 25 },
    { name: "hydroxyurea", potency: 250 }, { name: "imepitoin", potency: 100 },
    { name: "irbesartan", potency: 150 }, { name: "itraconazole", potency: 100 },
    { name: "lanthanum carbonate", potency: 750 }, { name: "leflunomide", potency: 20 },
    { name: "levetiracetam", potency: 500 }, { name: "levothyroxine (ug)", potency: 100 },
    { name: "loperamide", potency: 2 }, { name: "maropitant", potency: 16 }, { name: "maropitant", potency: 24 },
    { name: "meclizine", potency: 25 }, { name: "meloxicam", potency: 1 },
    { name: "methimazole", potency: 5 }, { name: "methocarbamol", potency: 750 },
    { name: "metoclo-pramide", potency: 3.84 }, { name: "metronidazole", potency: 250 },
    { name: "mirtazapine", potency: 16 }, { name: "misoprostol (ug)", potency: 200 },
    { name: "montelukast", potency: 10 }, { name: "mosapride", potency: 5 },
    { name: "mycophenolate(MMF)", potency: 250 }, { name: "nitrofurantoin", potency: 50 },
    { name: "omeprazole", potency: 20 }, { name: "ondansetron", potency: 8 },
    { name: "oxybutynin chloride", potency: 50 }, { name: "pentoxifylline", potency: 400 },
    { name: "phenobarbital", potency: 30 }, { name: "phenoxybenzamine", potency: 10 },
    { name: "pimobendan", potency: 5 }, { name: "piroxicam", potency: 10 },
    { name: "prednisolone (PDS)", potency: 5 }, { name: "pregabalin", potency: 75 }, { name: "pregabalin", potency: 150 },
    { name: "ramipril", potency: 5 }, { name: "rivaroxaban", potency: 10 },
    { name: "sevelamer carbonate", potency: 800 }, { name: "sildenafil", potency: 100 },
    { name: "silymarin", potency: 140 }, { name: "spironolactone", potency: 50 }
];